### ISSUE TITLE
plugin updates in the admin cp have blank fields

### ISSUE THREAD

**Issue by andrewjs18** [MyBBStuff/SimpleLikes#40]
in the admin cp>plugins>plugin update page, simple likes has several blank fields:

![149 03 31](https://user-images.githubusercontent.com/2748980/43999732-500bc062-9de0-11e8-9705-38ce76b1dd3b.jpg)

**Comment by euantorano** [comment]
I believe this information may be coming from the MyBB extend site, I will have to check.

**Comment by chack1172** [comment]
@euantorano after some tests I found that the issue is with codename. In plugin file you used `mybbstuff_simplelikes` but in the community mod page you use `MybbStuff_SimpleLikes`. So we have 3 options:
1. changing it in plugin file
2. changing it in mod site
3. changing mybb files making it case insensitive

**Comment by euantorano** [comment]
I’ll change it on the mods site, thanks.

**Comment by chack1172** [comment]
I think we should also fix it in mybb.

**Comment by andrewjs18** [comment]
I fixed it for @euantorano on the extend site.  Once it was fixed, it disappeared from the plugin updates page in the admin cp for obvious reasons.
